"""dtime reramed as d_time

Revision ID: 145acfca02a3
Revises: 91760c9876fb
Create Date: 2020-03-30 17:08:20.058856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '145acfca02a3'
down_revision = '91760c9876fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('d_time', sa.DateTime(), nullable=False))
    op.drop_column('appointments', 'dtime')
    op.add_column('messages', sa.Column('d_time', sa.DateTime(), nullable=False))
    op.drop_column('messages', 'dtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('dtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'd_time')
    op.add_column('appointments', sa.Column('dtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'd_time')
    # ### end Alembic commands ###
