"""MessageType added

Revision ID: 91760c9876fb
Revises: f64a71cab62a
Create Date: 2020-03-30 16:39:51.589578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91760c9876fb'
down_revision = 'f64a71cab62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    message_type = postgresql.ENUM('USER', 'BOT', name='messagetype')
    message_type.create(op.get_bind())
    op.add_column('messages', sa.Column('msg_type', sa.Enum('USER', 'BOT', name='messagetype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'msg_type')

    message_type = postgresql.ENUM('USER', 'BOT', name='messagetype')
    message_type.drop(op.get_bind())
    # ### end Alembic commands ###