"""User model modified

Revision ID: d24e1e56f563
Revises: 145acfca02a3
Create Date: 2020-03-31 09:22:21.365289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd24e1e56f563'
down_revision = '145acfca02a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=40), nullable=False))
    op.drop_column('users', 'first_access')
    op.drop_column('users', 'last_access')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_access', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_access', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'username')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
